---
title: "Discussion"
output:
  pdf_document: default
  html_document: default
  word_document: default
---
#Discussion
As described in the Introduction, our understanding of the mechanisms of learning, memory and perception requires appropriate model systems. The careful measurement of processes across multiple levels of organisation (from molecular, through circuits, to behaviour) can aid our understanding of these psychological proesses [@Clayton2009]. I introduced the zebra finch as an attractive model species, especially for auditory learning, memory and perception, in part because the zebra finch has had a particular impact in the study of vocal learning during the juvenile critical period [@Bolhuis2010; @Doupe1999; @Gobes2017; @Marler2000], and because the neuroanatomy and the genome of the zebra finch are fairly well understood [@Reiner2004; @Warren2010]. Over the last few decades, investigators have begun to apply operant conditioning paradigms in the zebra finch to study other forms of learning and perception that occur through the lifespan [@Beckers2003; @Bregman2016; @VanHeijningen2013].

Here I aimed to develop a rigorous base of technique and knowledge for operant conditioning studies of the zebra finch. My first aim was to determine whether auditory memories, after Go/No-Go operant conditioning, might be encoded differently in the auditory forebrain depending on the behaviour that was associated with the song. To do this, I worked in collaboration with the ten Cate laboratory at Leiden University and used a molecular technique for mapping neural activity (Chapter 2). My second aim was to thoroughly characterise the learning process itself, at a behavioural level (Chapter 5). To do this I first developed (Chapter 3) and validated (Chapter 4) a new hardware/software system for zebra finch operant conditioning. My third aim was to investigate whether the experience of hearing learned Go versus No-Go stimuli, in a non-reinforced context, elicits observable differences in behaviour that might confound interpretation of neural-level responses (Chapter 6).

##How are learned auditory associations encoded in the brain?
Previous literature into learning in zebra finches includes investigations of male song learning/copying, a time-limited process [for a review see @Gobes2017]. Zebra finches have also been used as a model species for a simple form of learning that continues through the lifespan: auditory habituation [for a review see @Dong2009]. For both of these forms of learning, the IEG _ZENK_ has been used as a proxy for activity. Starting with the finding that conspecific song playback induces IEG expression in a part of the zebra finch brain now referred to as the auditory forebrain [@Mello1992], researchers have found increasingly complex roles for the auditory forebrain in song representation [@Avey2005a; @Jarvis1995a; @Kruse2004; @Mello1995]. Here I used _ZENK_ as a proxy for activity after operant conditioning, a form of associative learning that continues through the lifespan. There has been previous interest in understanding the neurological response to operant conditioning in songbirds [@Bell2015; @Gentner2003; @Gentner2004] and one of these studies similarly used _ZENK_ as a proxy for activity in an operant conditioning experiment, though that study was conducted on male starlings and confounded stress and associative learning by testing stimuli during maintenance or reversal learning [@Gentner2004]. Here I conducted a more refined experiment, measuring the _ZENK_ response to auditory stimuli in an unreinforced context where active learning no longer occurs.

In Chapter 2, I trained birds to discriminate between two songs using operant conditioning, and analysed the expression of the IEG _ZENK_ after passive acute exposure to a Go song, a No-Go song, a habituated song, or a novel song. I found great individual differences in _ZENK_ response, but showed that these did not relate to the playback condition. To our knowledge, this is the first evidence that the novel/familiar difference in _ZENK_ expression across the auditory forebrain is not absolute. This characterisation of molecular and neuroanatomical responses to operantly conditioned song playbacks enhances the current literature, which has previously focused on active learning rather than on passive exposure to previously learned songs [e.g. @Gentner2003; @Jarvis1995a]. It is possible that there is no differential IEG response across our four conditions once a bird has fully habituated to a song attenuation chamber. However, it is also possible that _ZENK_ is not the right gene to detect these differences in this context. To that end, there are findings from an allied RNA-Seq study suggesting that expression levels for some genes (though not _ZENK_) do vary between the Go and the No-Go conditions [@George2018].

Though I found that the category of playback did not alter the overall levels of _ZENK_ expression in the auditory forebrain, I did show that the Go song elicited a more coordinated response in the auditory forebrain than any of the three other conditions. This is an intriguing finding; perhaps there is functional structure within the auditory forebrain that results in different patterns of correlated activity depending on stimulus association. The auditory forebrain is a small part of the songbird brain with high connectivity between regions [@Vates1996], and gaps remain in our understanding of the boundaries between regions (as reviewed in Section 2.1.2).

As such, this was a suitable problem for the application of graph theoretical approaches. The use of graph theory to discover neural patterns of activity is not novel [@Tanimizu2017], though this is believed to be the first use of graph theory to find central vertices, or regions that correlate with many other regions, within the songbird auditory forebrain. I found that for the Go response only, lateral CMM was the most central vertex, indicating that lateral CMM either drives or simply reflects activity in other regions within the auditory forebrain in response to Go songs. Lateral CMM did not have this relationship with other auditory forebrain regions for the other conditions. This finding elicits a clear hypothesis: does lateral CMM drive coordinated activity across the auditory forebrain? Future work could test this through the use of electrophysiology, measuring the timing of neural activity in lateral CMM and other regions.

One concern in the interpretation of the enhanced coordination of _ZENK_ response to the Go stimulus relates to the question of what _ZENK_ expression actually reflects in this context. IEG expression in the zebra finch auditory forebrain has been shown to reflect both novel [@Mello1992] and previously learned stimuli [@Gentner2004]. In this context, where the stimulus discrimination has been previously learned but is no longer being actively maintained, the _ZENK_ response could be functioning either as a read-out of the memory [e.g. @Liu2012] or it could be assisting in the formation of a new memory [@Minatohara2016]. Though we specifically chose the number of song repetitions to reduce the likelihood of extinction learning [e.g. @Jarvis1995a], we cannot rule out the possibility that the _ZENK_ expression in response to these passive playbacks reflects that. Future research would ideally explicitly address this, by testing some individuals with passive exposure and other individuals still engaged with the operant apparatus, although this would raise complications related to motor behaviours and motivation. 

##Can behaviour during operant conditioning enhance our understanding of the learning process?
In Chapter 3, I described the building of Operanter, open source hardware and software for avian operant conditioning. Currently available systems for operant conditioning on the market either rely on proprietary software and/or hardware components [@Pineno2014; @Tchernichovski2000], or are narrowly designed to function for one specific purpose [@OpenBeh]. In collaboration with colleagues with electronics and software programming experience, I developed a suite of Java-based software and non-proprietary hardware designed to function with manufacturer-independent components. This software and hardware is versatile, easily extendable, and inexpensive, and those features will allow researchers with small budgets or specific requirements to build operant conditioning setups. In Chapter 4, I showed that Operanter can be used to successfully train zebra finches to discriminate between two conspecific songs. I compared birds trained using the Operanter system with birds trained using a proprietary system at Leiden University, and demonstrated that the asymptotic learning of Operanter birds was lower than the asymptotic learning of Leiden birds.

For Chapter 5, I trained birds using Operanter, and characterised their learning of the Go/No-Go discrimination. Most fundamentally, I confirmed that Go/No-Go training leads to discrimination learning for female zebra finches. I also found evidence from both learning and maintenance trials that the Go and No-Go stimuli require different psychological processes. I highlighted large individual differences in when birds prefer to be active, and showed that those preferences correlate with learning rate. Finally, I found that the time of day, inter-trial interval duration, accuracy of the preceding trial and stimulus stype all predict the accuracy of response during maintenance of discrimination. I concluded that researchers using Go/No-Go operant conditioning for zebra finches should be conservative when setting learning criteria, and should alter the maximum response latency in light of my findings.

The research described in Chapters 4 and 5 fits in with a wealth of previous literature about the mechanisms underlying operant conditioning [@Herrnstein1961; @Kalenscher2005; @Skinner1938; @Thomas2009; @Yechiam2006]. Through the training of nearly three dozen female zebra finches, I acquired a large dataset of simple operant conditioning learning and maintenance behaviours. Though the experiments were not explicitly designed to test hypotheses about the psychological mechanisms behind operant conditioning, exploratory interrogation of this behavioural data allowed me to characterise multiple features of operant conditioning learning and behaviour. The findings have multiple implications for experimenters using operant conditioning to test avian perception.

Given the evidence I found for differential learning of Go and No-Go stimuli, I suggest that researchers use conservative metrics for establishing a learning criterion. That is, as birds tend to respond more accurately to Go stimuli than No-Go stimuli earlier in the learning process, if experimenters want to ensure that both the Go and No-Go stimuli have been learned, they should set learning criterions based on either the percentage correct for both Go and No-Go, or bias metrics [@Alves-Pinto2012; @Wickens2001]. Experimenters should also be aware that asymptotic accuracy levels may be depressed by turning off the operant conditioning apparatus in the afternoon, which they may be requested to do for animal welfare purposes. This depression in accuracy is significant, and may cause difficulty in experiments where small differences in responses to probe stimuli are sought [e.g. @Chen2015a]. This evidence could therefore be used to argue that operant conditioning should occur throughout the entire photoperiod in order to increase the power of the research and reduce the number of animals required to find an effect.

One series of findings directly addresses the impact that time of day has on operant conditioning response behaviours. I found that there was great individual variation in the time of day that birds initiated trials, and that birds that were preferentially active in the morning tended to learn the discrimination more slowly than birds preferentially active later in the day. I also found that birds were more accurate in the early part of the day than the later part of the day, and that time of day also interacted whether the bird was accurate on the preceding trial to determine accuracy. That is, birds are more likely to refer to the preceding trial during the later part of the day than during the early part of the day. When viewed in a attention framework [e.g. @Ammons1995], these findings together suggest that learning, and therefore response accuracy, may be facilitated by birds being allowed to initiate trials throughout the day for two reasons. First, one explanation for the learning rate effect may be that birds that are preferentially active in the morning are slower at learning the discrimination because they have a longer gap between the bulk of their trials and the next morning. This gap would be attenuated by allowing the birds to initiate trials throughout the photoperiod. Second, if birds refer to the preceding trial during the later part of the day to inform responding but not during the earlier part of the day, response accuracy during maintenance might be improved by increasing the number of trials that birds can initiate during the later part of the day.

Future research should extend the present findings by experimentally manipulating the time of day effect. One potential experimental design involves altering the times of day during which the birds can engage with the operant apparatus. Three groups should be used: morning (e.g. 7:00-13:00), afternoon (e.g. 13:00-19:00) and split (7:00-10:00, 16:00-19:00). If the time of day learning rate effect is caused by the morning-active birds having a long gap between the bulk of their trials and the next morning, the morning and the afternoon groups will learn similarly slowly, with the split group learning more quickly. However, if the time of day effects demonstrated in this thesis are are caused or mediated by attentional shifts throughout the circadian rhythm, the morning group will learn the slowest and the afternoon group will learn the fastest, as the afternoon group will be most able to avail of accuracy information from the preceding trial; the split group will learn at a rate between the morning and afternoon groups. In this way, the cause of the learning rate effects can be determined to be attentional or due to the spacing of inter-trial intervals.

I also found a pattern of responses latencies to Go and No-Go stimuli during learning and maintenance that, to my knowledge, has not been previously reported. These differential patterns support models of Go/No-Go discrimination learning that state that Go and No-Go stimuli are learned differentially and that discrimination of Go and No-Go songs is therefore two learning processes, and not one unitary process [@Yechiam2006]. On a more practical level, researchers should limit the response window to 3000 ms after the stimulus presentation to avoid the capture of responses to No-Go stimuli that may be due to boredom, impatience or the forgetting of the most recent stimulus. Limiting the response window will ensure that most captured responses will be true "false positives", whereby a bird produces a genuine incorrect response. By making this change, researchers using probe-trial type studies will more accurately assign responses to probes to either the Go or the No-Go response category.

##Do behaviours in non-reinforced contexts correlate with neural processes in the same context?
After describing very subtle differences in _ZENK_ expression activity in response to the song playbacks, it was critical to consider factors that may confound the interpretation of the coordinated _ZENK_ activity. I therefore sought to characterise the behavioural response to the same unsolicited song playback that was used in the measurement of _ZENK_ study. In Chapter 6, I trained a separate group of birds, and recorded their responses to acute passive song playback after learning the Go/No-Go discrimination. I found no evidence that the birds respond differentially to Go and No-Go song playback in this context. I also found no evidence for a behavioural response to the song playback at all, as overall activity levels were similar before and during playback. 

These findings directly contrast with previous published literature, where the birds froze for minutes upon hearing a conspecific song, even following habituation [@Stripling2003]. These birds' extensive habituation, which occurred over a period of weeks as described in Chapter 5, may be a sufficiently different process to the habituation described by Stripling et al. (2003). The birds here actively initiated song playbacks, whereas birds in Stripling et al. (2003) were passively exposed for the habituation procedure. Future research could examine whether this could cause a differential response to non-solicited presentation of one of those songs.

##Integrating findings across three aims
As a whole, development of the Operanter system provided the opportunity to train multiple female zebra finches in order to conduct behavioural analyses. The findings from Chapter 5, that Go and No-Go stimuli are learned differentially, inform our understanding of _ZENK_ expression after discrimination learning. By showing that the response latencies to Go and No-Go stimuli are different, and that correct responses to Go and No-Go stimuli are learned at different rates, we add increasing evidence to the body of literature [e.g. @Roy2009] that states that not only do subjects learn to associate one stimulus with a reward and the other stimulus with a punishment, but that these are also learned in different ways. Therefore, _ZENK_ expression in response to the playback of a trained stimulus may reflect either the association (i.e. food reward or darkness punishment), or it may reflect the difference between the processes necessary to respond correctly to Go and No-Go stimuli.

Further, the findings from Chapter 6, that the passive acute song playback does not induce a discrete behavioural state and that there is no evidence for an increase in stress-related behaviours, also inform our understanding of _ZENK_ expression in response to the same passive acute playback. We interpret the _ZENK_ expression results as reflecting neural activity and not physical activity for two reasons. First, there could be brain-wide changes due to metabolic demand [@Tong2001], so the findings in Chapter 6 allow us to rule out a shift in _ZENK_ expression in the auditory forebrain due to large-scale changes. Second, neural _ZENK_ expression can be induced by physical activity, but this is limited to motor regions [@Clark2011; @Feenders2008; @Jarvis1997], and the regions assessed here are auditory regions [see @Dong2008 for evidence that _ZENK_ expression in the auditory forebrain is not related to behavioural response]. Additionally, stress levels can alter the basal level of _ZENK_ [@Park2002], which has likely confounded previous studies of associative learning in the auditory forebrain [@Gentner2004; @Jarvis1995a]. Though we did not present novel or habituated songs to the birds in Chapter 6, the lack of evidence for any kind of a behavioural response to the unsolicited passive playback of Go or No-Go songs suggests that the playback of any conspecific song to a bird who has previously been engaged in operant conditioning of conspecific songs is not particularly surprising or alarming. With no behavioural evidence for increases in stress in response to acute playback of the punished song, we can interpret differences between _ZENK_ expression patterns to Go and No-Go stimuli as representing the categorical differences between the stimuli, and not simply varying stress levels.

Therefore, the _ZENK_ expression results from Chapter 2 can be interpreted with increased confidence to reflect a neural response to the stimulus category. On the basis of this evidence, we believe that the lack of a difference in overall _ZENK_ expression levels in the auditory forebrain is due to similar levels of novelty, and therefore salience, of all of the conditions. That is, the unsolicited and rapid nature of all of the song playbacks may have rendered the novel condition insufficiently different from even the habituated condition [@Kruse2004]. In this context, where female birds have habituated to social isolation over a period of weeks, novel and habituated conspecific songs give rise to the same overall levels of _ZENK_ expression in the auditory forebrain, perhaps reflecting the sparseness of conspecific song exposure over a long period.

One limitation of the current research is that the birds in Chapters 2, 5 and 6 were trained in different cohorts, and it is therefore impossible to conclude with certainty that the behaviour of the birds used for _ZENK_ expression analysis was the same as those in the behaviour analyses. Additionally, with only five birds per condition in the analysis of behavioural response to passive song playback, and five or six birds per condition in the analysis of _ZENK_ expression, we did not have the power to detect subtle changes. However, as there were numerous precedents for large effects on _ZENK_ expression [@Mello1992; @Mello1995], and previous similar studies regularly use four to six individuals per condition [@Gentner2004; @Ribeiro1998], we suggest that this was an appropriate decision.

Additionally, it remains unclear whether the birds learned to prefer the Go song during the operant conditioning, or whether the coordinated _ZENK_ response to Go songs is due to the learning of the Go response. To test this idea, and to therefore be able to interpret the findings in the context of the female song preference literature [@Leitner2005; @Woolley2008], song preference could be tested before and after Go/No-Go training using the same operant setup [@Holveck2007].

##Conclusion
In this thesis, I sought to integrate behavioural, neuroanatomical and neurogenomic data to enable a holistic investigation of operant conditioning, a form of learning available to adult zebra finches. This thesis provides the first evidence that in response to passive playback following the operant conditioning of two conspecific songs, _ZENK_ expression in the auditory forebrain is more coordinated to Go songs than to No-Go songs; therefore, operant conditioning does subtly alter the neurogenomic response to song presentation. I also demonstrated that acute song playback of novel and habituated songs does not necessarily drive differential expression of _ZENK_ in the zebra finch auditory forebrain, nor does it drive a differential behavioural response. 

Though it is frequently used as a simple and clean way to test perceptual abilities [@Lohr1998; @VanHeijningen2013], operant conditioning is a complex form of learning, and the measures presently used are unlikely to fully capture the experience of the subject. In order to rectify this, I deeply characterised the behaviour involved in learning a discrimination through operant conditioning, demonstrating complex relationships between factors including learning rate, the time of day, and recent preceding activity. In sum, my results suggest that Go/No-Go operant conditioning may drive two distinct types of learning, which may be reflected in subtle variations in gene expression in the auditory forebrain.